on:
  workflow_dispatch:
    inputs:
      bump_type:
        required: true
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  release:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
      - run: git fetch --tags
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix shell nixpkgs#bun --command bun install
      - run: nix shell nixpkgs#bun --command bun run build
      - run: git describe --tags --abbrev=0
      - run: nix run nixpkgs#semver-tool bump ${{ github.event.inputs.bump_type }} $(git describe --tags --abbrev=0)
      - run: nix run nixpkgs#semver ${{ github.event.inputs.bump_type }}
      - run: gh release create $(nix run nixpkgs#semver ${{ github.event.inputs.bump_type }}) --generate-notes ./dist/netero-oauth-mock
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
