on:
  workflow_dispatch:
    inputs:
      bump_type:
        required: true
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  release:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - run: nix shell nixpkgs#bun --command bun install
      - run: nix shell nixpkgs#bun --command bun run build
      - run: gh release create $(nix run nixpkgs#semver ${{ github.event.inputs.bump_type }}) --generate-notes ./hash-files
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
