on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix run nixpkgs#prettier -- README.md .github --print-width 100 --check
      - run: nix run nixpkgs#biome -- format --error-on-warnings --indent-style=space --line-width=100
      - run: nix run nixpkgs#biome -- lint --error-on-warnings --skip complexity/noUselessLoneBlockStatements --skip lint/complexity/useLiteralKeys
      - run: nix run nixpkgs#typescript
      - run: nix run nixpkgs#bun -- run build
      - run: nix run nixpkgs#bun -- test
