on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun run format
      - run: bun run lint
      - run: bun run check
      - run: bun run build
      - run: bun test
